version: '3.8'

services:

  php:
    build: docker/php
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/di.loc

  nginx:
    image: nginx:1.19.8
    ports:
      - 80:80
    volumes:
      - ./:/var/www/di.loc
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf